Homework 2
================
Pangsibo Shen
9/24/2020

``` r
library(tidyverse)
```

    ## -- Attaching packages ------------------------------------------- tidyverse 1.3.0 --

    ## v ggplot2 3.3.2     v purrr   0.3.4
    ## v tibble  3.0.3     v dplyr   1.0.2
    ## v tidyr   1.1.2     v stringr 1.4.0
    ## v readr   1.3.1     v forcats 0.5.0

    ## -- Conflicts ---------------------------------------------- tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

## Problem 1

Read the Mr. Trashwheel dataset

``` r
trashwheel_df =
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-7-2020-1.xlsx",
    sheet = "Mr. Trash Wheel",
    range = cell_cols("A:N")) %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
```

Read precipitation data

``` r
precip_2018 =
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-7-2020-1.xlsx",
    sheet = "2018 Precipitation",
    skip = 1)%>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate(year)

precip_2017 =
  read_xlsx(
    "./data/Trash-Wheel-Collection-Totals-7-2020-1.xlsx",
    sheet = "2017 Precipitation",
    skip = 1)%>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate(year)
```

Now combine annual precipitation.

``` r
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  )

precip_df =
  bind_rows(precip_2018,precip_2017) 

left_join(precip_df, month_df, by = "month")
```

    ## # A tibble: 24 x 4
    ##     year month total month_name
    ##    <dbl> <dbl> <dbl> <chr>     
    ##  1  2018     1  0.94 January   
    ##  2  2018     2  4.8  February  
    ##  3  2018     3  2.69 March     
    ##  4  2018     4  4.69 April     
    ##  5  2018     5  9.27 May       
    ##  6  2018     6  4.77 June      
    ##  7  2018     7 10.2  July      
    ##  8  2018     8  6.45 August    
    ##  9  2018     9 10.5  September 
    ## 10  2018    10  2.12 October   
    ## # ... with 14 more rows

This dataset contains information from the Mr. Trashwheel trash
collector in Baltimore, Maryland. As trash enters the inner harbor, the
trashwheel collects that trash, and stores it in a dumpster. The dataset
contains information on year, month, and trash collected, include some
specific kinds of trash. There are a total of 416 rows in our final
dataset. Additional data sheets include month precipitation data.

## Problem 2

Read and clean the NYC Subway dataset

``` r
nyc_subway = read_csv("./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")%>%
  janitor::clean_names()%>%
  transform(route8 = as.character(route8),
          route9 = as.character(route9),
          route10 = as.character(route10),
          route11 = as.character(route11))%>%
  pivot_longer(route1:route11,
               names_to = "route_number",
               values_to = "route_names"
  )%>%
  drop_na(route_names)%>%
  select(c("line","station_name","station_latitude","station_longitude","route_number","route_names","entry", "vending", "entrance_type","ada"))%>%
  mutate(entry = recode(entry, "YES" = TRUE, "NO" = FALSE))%>%
  unique()
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_double(),
    ##   Route9 = col_double(),
    ##   Route10 = col_double(),
    ##   Route11 = col_double(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
head(nyc_subway)
```

    ## # A tibble: 6 x 10
    ##   line  station_name station_latitude station_longitu~ route_number route_names
    ##   <chr> <chr>                   <dbl>            <dbl> <chr>        <chr>      
    ## 1 4 Av~ 25th St                  40.7            -74.0 route1       R          
    ## 2 4 Av~ 36th St                  40.7            -74.0 route1       N          
    ## 3 4 Av~ 36th St                  40.7            -74.0 route2       R          
    ## 4 4 Av~ 45th St                  40.6            -74.0 route1       R          
    ## 5 4 Av~ 53rd St                  40.6            -74.0 route1       R          
    ## 6 4 Av~ 53rd St                  40.6            -74.0 route1       R          
    ## # ... with 4 more variables: entry <lgl>, vending <chr>, entrance_type <chr>,
    ## #   ada <lgl>

-----

How many distinct stations are there?

``` r
distinct(nyc_subway, station_name)
```

    ## # A tibble: 356 x 1
    ##    station_name            
    ##    <chr>                   
    ##  1 25th St                 
    ##  2 36th St                 
    ##  3 45th St                 
    ##  4 53rd St                 
    ##  5 59th St                 
    ##  6 77th St                 
    ##  7 86th St                 
    ##  8 95th St                 
    ##  9 9th St                  
    ## 10 Atlantic Av-Barclays Ctr
    ## # ... with 346 more rows

``` r
#distinct(nyc_subway, line)
#distinct(nyc_subway, route_names)
```

there are 356 distinct stations.

-----

How many stations are ADA compliant?

``` r
nyc_subway%>%
  filter(ada == TRUE)%>%
  distinct(station_name)%>%
  nrow()
```

    ## [1] 73

There are 73 stations with ADA compliant.

-----

What proportion of station entrances / exits without vending allow
entrance?

``` r
no_venting = nyc_subway%>%
  filter(vending == "NO")%>%
  nrow() #number of station entrances/exists without vending allow entrance

venting_prop = no_venting/nrow(nyc_subway) 
venting_prop*100 
```

    ## [1] 17.7678

This is 17.77% of station entrances/exits don’t have vending allow
entrance.

-----

How many distinct stations serve the A train? Of the stations that serve
the A train, how many are ADA compliant?

``` r
nyc_subway%>%
  filter(route_names == "A")%>%
  distinct(station_name)%>%
  nrow()
```

    ## [1] 56

``` r
nyc_subway%>%
  filter(route_names == "A" & ada == TRUE)%>%
  distinct(station_name)%>%
  nrow()
```

    ## [1] 16

There are 56 distinct stations serve the A train and 16 of them are ADA
compliant.
